build:
	arch -x86_64 gcc -g -L ./lib/mlx -lmlx -framework OpenGl -framework Appkit ./src/*.c ./lib/libft/*.c ./lib/gnl/*.c
bonus:
	arch -x86_64 gcc -g -L ./lib/mlx -lmlx -framework OpenGl -framework Appkit ./src_bonus/*.c ./lib/libft/*.c ./lib/gnl/*.c